# Generated by Django 5.2.7 on 2026-05-22 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentprofile_year_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the implicit M2M join table; the through table below replaces it.
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS main_community_members;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'community')},
            },
        ),
        # Update only the ORM state — no schema change needed (RunSQL above handled it).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='community',
                    name='members',
                    field=models.ManyToManyField(blank=True, related_name='joined_communities', through='main.CommunityMembership', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]
