# Generated by Django 5.2.7 on 2026-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_communitymembership_alter_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
