# Generated by Django 5.2.7 on 2026-05-20 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_peerlyuser_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='peerlyuser',
            managers=[
            ],
        ),
    ]
